apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: zeus-avax-client
    app.kubernetes.io/managed-by: zeus
    app.kubernetes.io/name: zeus-avax-client
  name: zeus-avax-client
spec:
  ports:
  - name: hercules
    port: 9003
    protocol: TCP
    targetPort: hercules
  - name: p2p-tcp
    port: 9651
    protocol: TCP
    targetPort: p2p-tcp
  - name: http-api
    port: 9650
    protocol: TCP
    targetPort: http-api
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-api
  selector:
    app.kubernetes.io/instance: zeus-avax-client
    app.kubernetes.io/name: zeus-avax-client
  type: ClusterIP
status:
  loadBalancer: {}
