apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: zeus-consensus-client
    app.kubernetes.io/managed-by: zeus
    app.kubernetes.io/name: zeus-consensus-client
    version: version-1671079153579521629
  name: zeus-consensus-client
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: zeus-consensus-client
      app.kubernetes.io/name: zeus-consensus-client
  serviceName: zeus-consensus-client
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: zeus-consensus-client
        app.kubernetes.io/name: zeus-consensus-client
        version: version-1671079153579593547
    spec:
      containers:
      - args:
        - -c
        - /scripts/start.sh
        command:
        - /bin/sh
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: sigp/lighthouse:v3.3.0-modern
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 120
          tcpSocket:
            port: http-api
        name: zeus-consensus-client
        ports:
        - containerPort: 9000
          name: p2p-udp
          protocol: TCP
        - containerPort: 9000
          name: p2p-tcp
          protocol: TCP
        - containerPort: 5054
          name: metrics
          protocol: TCP
        - containerPort: 5052
          name: http-api
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: http-api
        resources: {}
        volumeMounts:
        - mountPath: /scripts
          name: cm-consensus-client
        - mountPath: /data
          name: consensus-client-storage
        - mountPath: /jwt
          name: jwt
      - args:
        - -c
        - hercules
        command:
        - /bin/sh
        image: zeusfyi/hercules:latest
        imagePullPolicy: Always
        name: hercules
        ports:
        - containerPort: 9003
          name: hercules
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /scripts
          name: cm-consensus-client
        - mountPath: /data
          name: consensus-client-storage
        - mountPath: /jwt
          name: jwt
      initContainers:
      - args:
        - -c
        - /scripts/download.sh
        command:
        - /bin/sh
        image: zeusfyi/hercules:latest
        imagePullPolicy: Always
        name: init-snapshot
        resources: {}
        volumeMounts:
        - mountPath: /scripts
          name: cm-consensus-client
        - mountPath: /data
          name: consensus-client-storage
        - mountPath: /jwt
          name: jwt
      - command:
        - chown
        - -R
        - 10001:10001
        - /data
        image: busybox:1.34.0
        imagePullPolicy: IfNotPresent
        name: init-chown-data
        resources: {}
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - mountPath: /data
          name: consensus-client-storage
      shareProcessNamespace: true
      volumes:
      - configMap:
          defaultMode: 484
          name: cm-consensus-client
        name: cm-consensus-client
      - emptyDir:
          sizeLimit: 1Mi
        name: jwt
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: consensus-client-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
    status: {}
status:
  availableReplicas: 0
  replicas: 0
