apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: zeus-consensus-client
    app.kubernetes.io/managed-by: zeus
    app.kubernetes.io/name: zeus-consensus-client
    version: version-1671063533472950603
  name: zeus-consensus-client
spec:
  ports:
  - name: http-api
    port: 5052
    protocol: TCP
    targetPort: http-api
  - name: metrics
    port: 5054
    protocol: TCP
    targetPort: metrics
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-api
  - name: hercules
    port: 9003
    protocol: TCP
    targetPort: hercules
  - name: p2p-tcp
    port: 9000
    protocol: TCP
    targetPort: p2p-tcp
  - name: p2p-udp
    port: 9000
    protocol: UDP
    targetPort: p2p-udp
  selector:
    app.kubernetes.io/instance: zeus-consensus-client
    app.kubernetes.io/name: zeus-consensus-client
  type: ClusterIP
status:
  loadBalancer: {}
