apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: zeus-exec-client
    app.kubernetes.io/managed-by: zeus
    app.kubernetes.io/name: zeus-exec-client
    version: version-1672294145092439684
  name: zeus-exec-client
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: zeus-exec-client
      app.kubernetes.io/name: zeus-exec-client
  serviceName: zeus-exec-client
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: zeus-exec-client
        app.kubernetes.io/name: zeus-exec-client
        version: version-1672294145092494779
    spec:
      containers:
      - args:
        - -c
        - /scripts/start.sh
        command:
        - /bin/sh
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: ethereum/client-go:v1.10.26
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 120
          tcpSocket:
            port: http-rpc
        name: zeus-exec-client
        ports:
        - containerPort: 6060
          name: metrics
          protocol: TCP
        - containerPort: 8545
          name: http-rpc
          protocol: TCP
        - containerPort: 8546
          name: ws-rpc
          protocol: TCP
        - containerPort: 30303
          name: p2p-tcp
          protocol: TCP
        - containerPort: 30303
          name: p2p-udp
          protocol: TCP
        - containerPort: 8551
          name: auth-rpc
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: http-rpc
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: exec-client-storage
        - mountPath: /scripts
          name: cm-exec-client
      - args:
        - -c
        - /scripts/hercules.sh
        command:
        - /bin/sh
        image: zeusfyi/hercules:latest
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 120
          tcpSocket:
            port: hercules
        name: hercules
        ports:
        - containerPort: 9003
          name: hercules
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: exec-client-storage
        - mountPath: /scripts
          name: cm-exec-client
      initContainers:
      - args:
        - -c
        - /scripts/download.sh
        command:
        - /bin/sh
        image: zeusfyi/hercules:latest
        imagePullPolicy: Always
        name: init-snapshot
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: exec-client-storage
        - mountPath: /scripts
          name: cm-exec-client
      - command:
        - chown
        - -R
        - 10001:10001
        - /data
        image: busybox:1.34.0
        imagePullPolicy: IfNotPresent
        name: init-chown-data
        resources: {}
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - mountPath: /data
          name: exec-client-storage
      volumes:
      - configMap:
          defaultMode: 484
          name: cm-exec-client
        name: cm-exec-client
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: exec-client-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    status: {}
status:
  availableReplicas: 0
  replicas: 0
