apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: zeus-exec-client
    app.kubernetes.io/managed-by: zeus
    app.kubernetes.io/name: zeus-exec-client
    version: version-1671064865797176251
  name: zeus-exec-client
spec:
  ports:
  - name: ws-rpc
    port: 8546
    protocol: TCP
    targetPort: ws-rpc
  - name: auth-rpc
    port: 8551
    protocol: TCP
    targetPort: auth-rpc
  - name: metrics
    port: 6060
    protocol: TCP
    targetPort: metrics
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-rpc
  - name: hercules
    port: 9003
    protocol: TCP
    targetPort: hercules
  - name: p2p-tcp
    port: 30303
    protocol: TCP
    targetPort: p2p-tcp
  - name: p2p-udp
    port: 30303
    protocol: UDP
    targetPort: p2p-udp
  - name: http-rpc
    port: 8545
    protocol: TCP
    targetPort: http-rpc
  selector:
    app.kubernetes.io/instance: zeus-exec-client
    app.kubernetes.io/name: zeus-exec-client
  type: ClusterIP
status:
  loadBalancer: {}
