apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: zeus-web3signer
    app.kubernetes.io/managed-by: zeus-web3signer
    app.kubernetes.io/name: zeus-web3signer
    version: version-1672525754884830085
  name: zeus-web3signer
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: "9000"
  selector:
    app.kubernetes.io/instance: zeus-web3signer
    app.kubernetes.io/name: zeus-web3signer
  type: ClusterIP
status:
  loadBalancer: {}
