kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nvme-ssd-block
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  zone: nyc1
provisioner: external/digitalocean