apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-cosmos-client
data:
  start.sh: |-
    #!/bin/sh
    exec gaiad start --home=/ --db_dir=/data --log_format=json --x-crisis-skip-assert-invariants --p2p.seeds="639d50339d7045436c756a042906b9a69970913f@seed-01.theta-testnet.polypore.xyz:26656,3e506472683ceb7ed75c1578d092c79785c27857@seed-02.theta-testnet.polypore.xyz:26656"
  download.sh: |-
    #!/bin/sh
    exec snapshots --downloadURL="" --clientName="cosmosClient" --network="theta-testnet-001" --protocol="cosmos"
  hercules.sh: |-
    #!/bin/sh 
    hercules
