# This is a sample config file for the serverless build.

# AWS settings (if using aws automation)
AWS_ACCOUNT_NUMBER: ""
AWS_ACCESS_KEY: ""
AWS_SECRET_KEY: ""

# AWS Lambda Values (if you have a lambda function, otherwise you can let the app install and generate these values for you)
AWS_LAMBA_FUNC_URL: ""
AWS_LAMBDA_INVOKE_ACCESS_KEY: ""
AWS_LAMBDA_INVOKE_SECRET_KEY: ""

# Age encryption private, public key values used to encrypt all your validator keys in a single file.
# If you don't have one, you can let the app generate one for you. If using the aws automation, it will also save
# it in secret manager for you as well
AGE_PRIVKEY: ""
AGE_PUBKEY: ""

# Validator network settings
NODE_URL: "https://eth.ephemeral.zeus.fyi"
NETWORK: "ephemery"
# Validator deposit & keystore generation settings
ETH1_PRIVATE_KEY: ""
# This eth1 key (ecdsa) is used to send the validator deposit txs, it should have 32 ETH + gas to send the txs per validator

MNEMONIC_24_WORDS: ""
HD_WALLET_PASSWORD: ""
# If you don't have one, you can let the app generate them for you.
# If using the aws automation, it will also save it in secret manager for you as well

VALIDATORS_COUNT: "3"
# If generating new keystores, e.g. you have generated 10 from your master hd seed,
# but now want to add 10 more, add the offset here to start from the Nth offset validator onwards
HD_OFFSET_VALIDATORS: ""

# Validator service values
BEARER: ""
# You need a bearer token to request validator service from us
# If you don't have one, you can request one from us
# Set a key group name to group your validators together
KEY_GROUP_NAME: ""
# By default, it uses this fee recipient address, for all your validators in your key group,
# but you can override it per validator if you want here:
# builds/serverless/aws_automation/validators_service_requests.go
FEE_RECIPIENT_ADDR: ""
