apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-sui
data:
  downloadMainnetNode.sh: |-
    #!/bin/sh
    exec snapshots --downloadURL="" --protocol="sui" --network="mainnet" --workload-type="full"
  downloadTestnetNode.sh: |-
    #!/bin/sh
    exec snapshots --downloadURL="" --protocol="sui" --network="testnet" --workload-type="full"
  fullnode.yaml: |-
    # Update this value to the location you want Sui to store its database
    db-path: "/data"

    network-address: "/dns/localhost/tcp/8080/http"
    metrics-address: "0.0.0.0:9184"
    # this address is also used for web socket connections
    json-rpc-address: "0.0.0.0:9000"
    enable-event-processing: true

    genesis:
      # Update this to the location of where the genesis file is stored
      genesis-file-location: "/data/genesis.blob"

    authority-store-pruning-config:
      num-latest-epoch-dbs-to-retain: 3
      epoch-db-pruning-period-secs: 3600
      num-epochs-to-retain: 1
      max-checkpoints-in-batch: 10
      max-transactions-in-batch: 1000
      pruning-run-delay-seconds: 60