apiVersion: v1
kind: Service
metadata:
  name: sui
  labels:
    app.kubernetes.io/name: sui
    app.kubernetes.io/instance: sui
    app.kubernetes.io/managed-by: zeus
spec:
  type: ClusterIP
  ports:
    - port: 9003
      targetPort: hercules
      protocol: TCP
      name: hercules
    - port: 8080
      targetPort: p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: 8081
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
    - port: 8082
      targetPort: p2p-udp-2
      protocol: UDP
      name: p2p-udp-2
    - port: 8084
      targetPort: p2p-udp-4
      protocol: UDP
      name: p2p-udp-4
    - port: 9000
      targetPort: http-rpc
      protocol: TCP
      name: http-rpc
    - port: 9184
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: sui
    app.kubernetes.io/instance: sui
