apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keydb-master-monitor
  labels:
    app: "keydb-master"
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "keydb-master"
      app.kubernetes.io/name: "keydb-master"
  endpoints:
    - port: metrics
      interval: 10s
      path: /metrics

