apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keydb-monitor
  labels:
    app: "keydb"
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "keydb"
      app.kubernetes.io/name: "keydb"
  endpoints:
    - port: metrics
      interval: 10s
      path: /metrics

