apiVersion: v1
kind: Service
metadata:
  name: "keydb-master"
  labels:
    app.kubernetes.io/instance: "keydb-master"
    app.kubernetes.io/name: "keydb-master"
    app.kubernetes.io/managed-by: "zeus"
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: keydb
      protocol: TCP
      name: keydb
    - port: 9121
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/instance: "keydb-master"
    app.kubernetes.io/name: "keydb-master"
