apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keydb
  labels:
    app: "keydb"
    app.kubernetes.io/name: keydb
    app.kubernetes.io/instance: keydb
    app.kubernetes.io/managed-by: zeus
  annotations:
    { }
spec:
  podManagementPolicy: OrderedReady
  replicas: 6
  selector:
    matchLabels:
      app: "keydb"
      app.kubernetes.io/name: keydb
      app.kubernetes.io/instance: keydb
  serviceName: keydb
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "keydb"
        app.kubernetes.io/name: keydb
        app.kubernetes.io/instance: keydb
    spec:
      containers:
        - name: "keydb"
          image: "zeusfyi/keydb:latest"
          volumeMounts:
            - mountPath: "/data"
              name: "keydb-storage"
            - mountPath: "/configs"
              name: "cm-keydb"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              # Get the pod's index from its hostname
              INDEX=$(hostname | awk -F'-' '{print $2}')
              
              # Compute the two indices for replication, wrapping around based on the replica count
              NEXT_INDEX=$(( ($INDEX + 1) % $REPLICA_COUNT ))
              NEXT_NEXT_INDEX=$(( ($INDEX + 2) % $REPLICA_COUNT ))
              
              # Append the replicaof configuration to the configuration file
              echo "replicaof keydb-$NEXT_INDEX.keydb.svc.cluster.local 6379" >> /configs/keydb.conf
              echo "replicaof keydb-$NEXT_NEXT_INDEX.keydb.svc.cluster.local 6379" >> /configs/keydb.conf
              
              # Start KeyDB with the dynamically generated configuration
              exec keydb-server /configs/keydb.conf
          env:
            - name: REPLICA_COUNT
              value: "6"
          ports:
            - name: "keydb"
              containerPort: 6379
              protocol: "TCP"
          livenessProbe:
            tcpSocket:
              port: keydb
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - keydb-cli
                - ping
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 3
          resources:
            limits:
              cpu: "200m"
              memory: 1Gi
            requests:
              cpu: "200m"
              memory: 1Gi
        - name: keydb-exporter
          image: oliver006/redis_exporter:v1.54.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 59000
            runAsGroup: 59000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 9121
              name: metrics
              protocol: TCP
      volumes:
        - name: cm-keydb
          configMap:
            name: cm-keydb
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: keydb-storage
        annotations:
          { }
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "50Gi"
