apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-geth
data:
  start.sh: |-
    #!/bin/sh
    exec sleep 100000000000000000
  download.sh: |-
    #!/bin/sh
    exec snapshot --downloadURL="" --clientName="geth"