apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-avax-client
data:
  start.sh: |-
    #!/bin/sh
    exec /avalanchego/build/avalanchego --db-dir=/data --http-host=0.0.0.0
  startFuji.sh: |-
    #!/bin/sh
    exec /avalanchego/build/avalanchego --db-dir=/data --http-host=0.0.0.0 --network-id=fuji
  download.sh: |-
    #!/bin/sh
    exec snapshots --downloadURL="" --clientName=""
  pause.sh: |-
    #!/bin/sh
    exec sleep 100000000000000000
  hercules.sh: |-
    #!/bin/sh 
    hercules
