apiVersion: v1
kind: Service
metadata:
  name: zeus-avax-client
  labels:
    app.kubernetes.io/name: zeus-avax-client
    app.kubernetes.io/instance: zeus-avax-client
    app.kubernetes.io/managed-by: zeus
spec:
  type: ClusterIP
  ports:
    - port: 9003
      targetPort: hercules
      protocol: TCP
      name: hercules
    - port: 9651
      targetPort: p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: 9650
      targetPort: http-api
      protocol: TCP
      name: http-api
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 80
      targetPort: http-api
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: zeus-avax-client
    app.kubernetes.io/instance: zeus-avax-client
