apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zeus-avax-client
  labels:
    app.kubernetes.io/name: zeus-avax-client
    app.kubernetes.io/instance: zeus-avax-client
    app.kubernetes.io/managed-by: zeus
  annotations:
    {}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zeus-avax-client
      app.kubernetes.io/instance: zeus-avax-client
  serviceName: zeus-avax-client
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zeus-avax-client
        app.kubernetes.io/instance: zeus-avax-client
    spec:
      initContainers:
        - name: init-chown-data
          image: "busybox:1.34.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "-R", "10001:10001", "/data"]
          resources:
            {}
          volumeMounts:
            - name: avax-client-storage
              mountPath: "/data"
        - name: init-snapshots
          image: "zeusfyi/hercules:latest"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/download.sh" ]
          resources:
            {}
          volumeMounts:
            - name: cm-avax-client
              mountPath: "/scripts"
            - name: avax-client-storage
              mountPath: "/data"
      containers:
        - name: hercules
          image: "zeusfyi/hercules:latest"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/hercules.sh" ]
          volumeMounts:
            - name: cm-avax-client
              mountPath: "/scripts"
            - name: avax-client-storage
              mountPath: "/data"
          ports:
            - name: hercules
              containerPort: 9003
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 120
            tcpSocket:
              port: hercules
        - name: zeus-avax-client
          image: "avaplatform/avalanchego:v1.9.10"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/start.sh" ]
          volumeMounts:
            - name: cm-avax-client
              mountPath: "/scripts"
            - name: avax-client-storage
              mountPath: "/data"
          ports:
            - name: p2p-tcp
              containerPort: 9651
              protocol: TCP
            - name: http-api
              containerPort: 9650
              protocol: TCP
            - name: metrics
              containerPort: 9090
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 120
            tcpSocket:
              port: http-api
          resources:
            {}
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      volumes:
        - name: cm-avax-client
          configMap:
            name: cm-avax-client
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: avax-client-storage
        annotations:
          {}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "2Ti"


