apiVersion: v1
kind: Service
metadata:
  name: sui-nodeport
  labels:
    app.kubernetes.io/name: sui
    app.kubernetes.io/instance: sui
    app.kubernetes.io/managed-by: zeus
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: 8084
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
  selector:
    app.kubernetes.io/name: sui
    app.kubernetes.io/instance: sui
