apiVersion: v1
kind: ConfigMap
metadata:
  name: local-static-provisioner-config
  namespace: default
  labels:
    helm.sh/chart: local-static-provisioner-2.0.0
    app.kubernetes.io/name: local-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-static-provisioner
data:
  storageClassMap: |
    # the name of local storage class
    nvme-ssd-block:
      # path to the directory of local volumes
      hostDir: /dev
      # the mount path of host directory in provisioner pod
      mountDir: /dev
      # If the local volume is a device, command configured here will be
      # used to clean it. This can be omitted and the default command
      # `/scripts/quick_reset.sh` will be used.
      blockCleanerCommand:
      - "/scripts/shred.sh"
      - "2"
      # The volume mode of PV. It defines whether a device volume is #
      # intended to use as a formatted filesystem volume or to remain in block
      # state. Value of Filesystem is implied when omitted.
      volumeMode: Filesystem
      # The filesystem to format before mounting on the node. This applies
      # only when the volume source is a device and mode is Filesystem.
      # The default value is to auto-select a filesystem in Kubernetes if unspecified.
      fsType: ext4
      # name pattern check
      # only discover file name matching pattern("*" by default).
      namePattern: "vda1"

