apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sui-monitor
  labels:
    app: "sui"
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "sui"
      app.kubernetes.io/name: "sui"
  endpoints:
    - port: metrics
      interval: 10s
      path: /metrics

