apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: zeus-us-west-1
  region: us-west-1

vpc:
  id: "vpc-your-vpc-id"
  securityGroup: "sg-your-security-group-id"
  subnets:
    private:
      us-west-1a:
        id: "subnet-your-subnet-id"
      us-west-1b:
        id: "subnet-your-subnet-id"


managedNodeGroups:
  - name: eks-pv-raid-ng
    labels: { fast-disk-node: "pv-raid" }
    instanceType: i3.4xlarge
    desiredCapacity: 1
    volumeSize: 20
    privateNetworking: true
    preBootstrapCommands:
      - |
        # Install NVMe CLI
        yum install nvme-cli -y
        
        # Get list of NVMe Drives
        nvme_drives=$(nvme list | grep "Amazon EC2 NVMe Instance Storage" | cut -d " " -f 1 || true)
        readarray -t nvme_drives <<< "$nvme_drives"
        num_drives=${#nvme_drives[@]}
        
        # Install software RAID utility
        yum install mdadm -y
        
        # Create RAID-0 array across the instance store NVMe SSDs
        mdadm --create /dev/md0 --level=0 --name=md0 --raid-devices=$num_drives "${nvme_drives[@]}"

        # Format drive with Ext4
        mkfs.ext4 /dev/md0

        # Get RAID array's UUID
        uuid=$(blkid -o value -s UUID /dev/md0)
        
        # Create a filesystem path to mount the disk
        mount_location="/mnt/fast-disks/${uuid}"
        mkdir -p $mount_location
        
        # Mount RAID device
        mount /dev/md0 $mount_location
        
        # Have disk be mounted on reboot
        mdadm --detail --scan >> /etc/mdadm.conf 
        echo /dev/md0 $mount_location ext4 defaults,noatime 0 2 >> /etc/fstab
