version: '3.8'

services:
  postgres:
    container_name: postgres_local_web3signer
    image: "postgres:15.1-bullseye"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
    driver: local