apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: zeus-validators
    app.kubernetes.io/managed-by: zeus
    app.kubernetes.io/name: zeus-validators
    version: version-1672723824829336623
  name: zeus-validators
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: zeus-validators
      app.kubernetes.io/name: zeus-validators
  serviceName: zeus-validators
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: zeus-validators
        app.kubernetes.io/name: zeus-validators
        version: version-1672723824829393701
    spec:
      containers:
      - args:
        - -c
        - /scripts/start.sh
        command:
        - /bin/sh
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: sigp/lighthouse:v3.3.0-modern
        imagePullPolicy: IfNotPresent
        name: zeus-validators
        ports:
        - containerPort: 5064
          name: metrics
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /scripts
          name: cm-validator-client
        - mountPath: /data
          name: validator-client-storage
      - args:
        - -c
        - /scripts/hercules.sh
        command:
        - /bin/sh
        image: zeusfyi/hercules:latest
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 120
          tcpSocket:
            port: hercules
        name: hercules
        ports:
        - containerPort: 9003
          name: hercules
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /scripts
          name: cm-validator-client
        - mountPath: /data
          name: validator-client-storage
      initContainers:
      - args:
        - -c
        - /scripts/download.sh
        command:
        - /bin/sh
        image: zeusfyi/hercules:latest
        imagePullPolicy: Always
        name: init-validator
        resources: {}
        volumeMounts:
        - mountPath: /scripts
          name: cm-validator-client
        - mountPath: /data
          name: validator-client-storage
      volumes:
      - configMap:
          defaultMode: 484
          name: cm-validator-client
        name: cm-validator-client
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: validator-client-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
status:
  availableReplicas: 0
  replicas: 0
