apiVersion: v1
kind: Service
metadata:
  name: zeus-cosmos-client-nodeport
  labels:
    app.kubernetes.io/name: zeus-cosmos-client
    app.kubernetes.io/instance: zeus-cosmos-client
    app.kubernetes.io/managed-by: zeus
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 26656
      targetPort: p2p-tcp
      nodePort: 30000
  selector:
    app.kubernetes.io/name: zeus-cosmos-client
    app.kubernetes.io/instance: zeus-cosmos-client
