name: Build Serverless BLS Signer

on:
  push:
    branches:
      - main
    paths:
      - apps/cookbooks/serverless/ethereum/bls_signatures/**

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Create directory and add dependent referenced external folder
      run: |
        mkdir -p apps/external
        cd apps/external
        git clone https://github.com/zeus-fyi/web3.git --branch master --single-branch

    - name: Build serverless bls signer app
      run: |
        cd apps/cookbooks/serverless/ethereum/bls_signatures
        go build -o main
        zip main.zip main

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v2
      with:
        name: main.zip
        path: main.zip
