name: Build Serverless BLS Signer

on:
  push:
    paths:
      - apps/cookbooks/serverless/ethereum/bls_signatures/**

env:
  AWS_REGION: us-west-1
  GO111MODULE: on
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 1
  SERVERLESS_IMG: zeusfyi
  SERVERLESS_NAME: ethereumbls
  SERVERLESS_LATEST: zeusfyi/ethereumbls:latest
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone external repos into workspace
      run: |
        mkdir -p apps/external
        cd apps/external
        git clone https://github.com/zeus-fyi/web3.git --branch master --single-branch

    - name: Cache Go Modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: go-mod-${{ hashFiles('**/go.sum') }}

    - name: Build Serverless BLS Signer
      run: |
        docker buildx build -t ${{ env.SERVERLESS_IMG }} -t ${{ env.SERVERLESS_LATEST }} --build-arg GOMODCACHE=${{ env.GOMODCACHE }} --build-arg GOCACHE=${{ env.GOCACHE }} --build-arg GOOS=${{ env.GOOS }} --build-arg GOARCH=${{ env.GOARCH }} --platform=${{ env.GOOS }}/${{ env.GOARCH }} -f docker/serverless/Dockerfile .

    - name: Copy Serverless BLS Signer Docker Binary
      run: |
        makefiles/aws_serverless/copy_docker_bin.sh

    - name: Zip Binary
      run: |
        zip main.zip main

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload the zip file to AWS Lambda
      run: |
        aws lambda update-function-code --function-name ${{ secrets.AWS_BLS_FUNCTION_NAME }} --zip-file fileb://main.zip > /dev/null

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v2
      with:
        name: main.zip
        path: main.zip
