name: Build Serverless BLS Signer

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-1
  GO111MODULE: on
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 1

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Set up Amazon Linux environment
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        sudo curl -o /etc/yum.repos.d/amazon-linux-2.repo https://amazon-linux-2-lts.s3.amazonaws.com/amazon-linux-2-lts.repo
        sudo apt-get install -y yum
        sudo yum install -y amazon-linux-extras
        sudo yum install -y make gcc

    - name: Cache Go Modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: go-mod-${{ hashFiles('**/go.sum') }}

    - name: Install zip
      run: |
        sudo apt-get update
        sudo apt-get install -y zip

    - name: Clone external repos into workspace
      run: |
        mkdir -p apps/external
        cd apps/external
        git clone https://github.com/zeus-fyi/web3.git --branch master --single-branch

    - name: Build Serverless BLS Signer
      run: |
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o main apps/cookbooks/serverless/ethereum/bls_signatures/main.go
        zip main.zip main

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload the zip file to AWS Lambda
      run: |
        aws lambda update-function-code --function-name ${{ secrets.AWS_BLS_FUNCTION_NAME }} --zip-file fileb://main.zip > /dev/null

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v2
      with:
        name: main.zip
        path: main.zip
