apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-validator-client
data:
  start.sh: |-
    #!/bin/sh
    exec lighthouse vc \
              --network mainnet \
              --log-format=JSON \
              --datadir=/validators \
              --http \
              --http-address=0.0.0.0 \
              --http-port=5062 \
              --beacon-nodes="http://zeus-consensus-client:5052"
  pause.sh: |-
    #!/bin/sh
    exec sleep 100000000000000000
  lighthouse.sh: |-
    #!/bin/sh
    exec lighthouse vc \
              --network mainnet \
              --log-format=JSON \
              --datadir=/validators \
              --http \
              --http-address=0.0.0.0 \
              --http-port=5062 \
              --beacon-nodes="http://zeus-consensus-client:5052"