apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zeus-validators
  labels:
    app.kubernetes.io/name: zeus-validators
    app.kubernetes.io/instance: zeus-validators
    app.kubernetes.io/managed-by: zeus
  annotations:
    {}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zeus-validators
      app.kubernetes.io/instance: zeus-validators
  serviceName: zeus-validators
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zeus-validators
        app.kubernetes.io/instance: zeus-validators
    spec:
      initContainers:
        - name: init-validator
          image: "zeusfyi/hercules:latest"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/download.sh" ]
          resources:
            { }
          volumeMounts:
            - name: cm-validator-client
              mountPath: "/scripts"
            - name: validator-client-storage
              mountPath: "/data"
      containers:
        - name: hercules
          image: "zeusfyi/hercules:latest"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","hercules" ]
          volumeMounts:
            - name: cm-validator-client
              mountPath: "/scripts"
            - name: validator-client-storage
              mountPath: "/data"
          ports:
            - name: hercules
              containerPort: 9003
              protocol: TCP
        - name: zeus-validators
          image: "sigp/lighthouse:v3.2.1-modern"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/start.sh" ]
          volumeMounts:
            - name: cm-validator-client
              mountPath: "/scripts"
            - name: validator-client-storage
              mountPath: "/data"
          ports:
            - name: metrics
              containerPort: 5054
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 120
            tcpSocket:
              port: metrics
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: metrics
          resources:
            {}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      volumes:
        - name: cm-validator-client
          configMap:
            name: cm-validator-client
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: validator-client-storage
        annotations:
          {}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "100Mi"


